Import("env_base", "env_etc")
import os

env = env_base.Clone(LIBS=env_etc.libm)

lib = env.StaticLibrary(
  target=["durandal"],
  source="""\
DistMatrix.cc
DistRange.cc
SimpPDB.cc
Singleton.cc
Stru.cc
rmsd.cc
""".splitlines())

for trg,src in [
      ("cluster_pdbs", "durandal"),
      ("rank_pdbs", "ranker")]:
  if (os.name == "nt"):
    trg += ".exe"
  env.Program(target="#bin/durandal.%s" % trg, source=[src+".cc", lib])
